### ISSUE TITLE
Create an Index for different topics

### ISSUE THREAD

**Issue by swiftlysingh** [Catalyst-IN/Awesome10-20_Database#7]
Create an index for different subjects and tracks such that it is easier to navigate this repo

**Comment by jyotijauhari** [comment]
Can u explain me what exactly we have to..
I want to work on this issue.

**Comment by swiftlysingh** [comment]
We have to create an index that will link to different fields. [You can look at this repo for reference.](https://github.com/public-apis/public-apis)

**Comment by jyotijauhari** [comment]
I want to work on this issue, can you assign it to me.
